//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class libmgmtEntities : DbContext
{
    public libmgmtEntities()
        : base("name=libmgmtEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Book> Books { get; set; }
    public virtual DbSet<book_order> book_order { get; set; }
    public virtual DbSet<Cart> Carts { get; set; }
    public virtual DbSet<order_detail> order_detail { get; set; }
    public virtual DbSet<UserInfo> UserInfoes { get; set; }
    public virtual DbSet<Wishlist> Wishlists { get; set; }
}
