//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Book
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Book()
    {
        this.Carts = new HashSet<Cart>();
        this.order_detail = new HashSet<order_detail>();
        this.Wishlists = new HashSet<Wishlist>();
    }

    public int auto_id { get; set; }
    public string title { get; set; }
    public string author { get; set; }
    public string publish_date { get; set; }
    public string image_path { get; set; }
    public string isbn { get; set; }
    public Nullable<bool> isNew { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Cart> Carts { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<order_detail> order_detail { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Wishlist> Wishlists { get; set; }
}

public partial class book_order
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public book_order()
    {
        this.order_detail = new HashSet<order_detail>();
    }

    public int auto_id { get; set; }
    public string user_id { get; set; }
    public Nullable<System.DateTime> order_time { get; set; }
    public string first_name { get; set; }
    public string last_name { get; set; }
    public string company { get; set; }
    public string tel { get; set; }
    public string fax { get; set; }
    public string country { get; set; }
    public string city { get; set; }
    public string post { get; set; }
    public string address_1 { get; set; }
    public string address_2 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<order_detail> order_detail { get; set; }
}

public partial class Cart
{
    public int auto_id { get; set; }
    public string user_id { get; set; }
    public Nullable<int> book_id { get; set; }
    public Nullable<bool> status { get; set; }

    public virtual Book Book { get; set; }
}

public partial class order_detail
{
    public int auto_id { get; set; }
    public Nullable<int> order_id { get; set; }
    public Nullable<int> book_id { get; set; }

    public virtual Book Book { get; set; }
    public virtual book_order book_order { get; set; }
}

public partial class UserInfo
{
    public int auto_id { get; set; }
    public string user_id { get; set; }
    public string first_name { get; set; }
    public string last_name { get; set; }
    public string tel { get; set; }
    public string fax { get; set; }
    public string country { get; set; }
    public string post { get; set; }
    public string city { get; set; }
    public string address_1 { get; set; }
    public string address_2 { get; set; }
    public string company { get; set; }
}

public partial class Wishlist
{
    public int auto_id { get; set; }
    public string user_id { get; set; }
    public Nullable<int> book_id { get; set; }
    public Nullable<bool> status { get; set; }

    public virtual Book Book { get; set; }
}
